/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Data {
  customOptionsBackgrounds: string[];
  tweaks: {
    [k: string]: Tweak;
  };
  [k: string]: unknown;
}
export interface Tweak {
  data: TweakData;
  files: string[];
  previewFiles: string[];
  x64support: boolean;
  [k: string]: unknown;
}
export interface TweakData {
  title: string;
  description: string;
  author: Author;
  category: string;
  version: string;
  [k: string]: unknown;
}
export interface Author {
  discord?: string | null;
  github?: string | null;
  email?: string | null;
  link?: string | null;
  [k: string]: unknown;
}
